services:
    zookeeper:
      image: zookeeper:3.5
    kafka:
      image: wurstmeister/kafka:2.13-2.8.1
      depends_on:
        - zookeeper
      environment:
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_LISTENERS=PLAINTEXT://:9092
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      healthcheck:
        test: /opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server kafka:9092 || exit
    exporter:
        build:
          context: .
        depends_on:
          kafka:
            condition: service_healthy
        restart: on-failure
        environment:
          - KAFKA_BROKERS=kafka:9092
          - PROMETHEUS_ADDR=:7979
          - REFRESH_INTERVAL=15
          - DEBUG=true
        ports:
          - "7979:7979"
